services:
  # Backend service
  - type: web
    name: mm-a2a-backend
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python backend_server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 5000
      - key: ENVIRONMENT
        value: production
      - key: GOOGLE_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true
    
  # Frontend service (nếu có)
  - type: web
    name: mm-a2a-frontend
    env: static
    region: singapore
    plan: free
    buildCommand: cd mm-front-ts && npm install && npm run build
    staticPublishPath: ./mm-front-ts/dist
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: VITE_API_URL
        value: https://mm-a2a-backend.onrender.com
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 